document.writeln("<div class=\'contactBox\' id=\'contactBox\'>");
document.writeln("      <img class=\'logo\' src=\'../assets/images/eicon1.png\' />");
document.writeln("      <div class=\'ct\'>");
document.writeln("      	<ul class=\'iconBox\'>");
document.writeln("      	  <li>");
document.writeln("      	    <a href=\'\'>");
document.writeln("      	      WeChat");
document.writeln("      	    </a>");
document.writeln("      	  </li>");
document.writeln("      	  <li>");
document.writeln("      	    <a href=\'\'>");
document.writeln("      	      Email");
document.writeln("      	    </a>");
document.writeln("      	  </li>");
document.writeln("      	  <li>");
document.writeln("      	    <a href=\'\'>");
document.writeln("      	      Telegram");
document.writeln("      	    </a>");
document.writeln("      	  </li>");
document.writeln("      	  <li class=\'airportIcon\'>");
document.writeln("      	    <!--<img class=\'airportQrcode\' src=\'../assets/images/commendus.jpeg\' alt=\'\'></li>-->");
document.writeln("      	    Twitter");
document.writeln("      	  <li>");
document.writeln("      	    <a href=\'\'>");
document.writeln("      	      Medium");
document.writeln("      	    </a>");
document.writeln("      	  </li>");
document.writeln("      	  <li>");
document.writeln("      	    <a href=\'\'>");
document.writeln("      	      Discord");
document.writeln("      	    </a>");
document.writeln("      	  </li>");
document.writeln("      	</ul>");
document.writeln("      	<div class=\'footerText \'>©InWeCrypto 2018</div>");
document.writeln("      </div>");
document.writeln("    </div>");